version: '3.9'

services:

  bot_admin_service:
    extends:
      file: ../src/bot_admin_service/docker-compose.yml
      service: bot_admin_service
    env_file:
      - ../.env

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 3600 1 300 100 60 10000
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  postgresql:
    image: bitnami/postgresql:latest
    hostname: postgresql
    ports:
      - '5432:5432'
    env_file:
      - ../src/bot_admin_service/.env
    volumes:
      - ./postgresql/conf/override.conf:/opt/bitnami/postgresql/conf/conf.d/override.conf
      - postgres-data:/bitnami/postgresql
    restart: always
    depends_on:
      - pgbouncer
    healthcheck:
      test: pg_isready -U admin
      interval: 2s
      timeout: 3s
      retries: 40

  pgbouncer:
    image: bitnami/pgbouncer:latest
    hostname: pgbouncer
    ports:
      - "6432:6432"
    env_file:
      - ../src/bot_admin_service/.env
    environment:
      - POSTGRESQL_HOST=postgresql
    volumes:
      - ./pgbouncer/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
    restart: always

volumes:
  redis-data:
    labels:
      keep:
  postgres-data:
    labels:
      keep: