version: '3.9'

services:

  bot_admin_service:
    extends:
      file: ../src/bot_admin_service/docker-compose.yml
      service: bot_admin_service
    environment:
      - STAGE=prod
      - MAX_WORKERS=1
    env_file:
      - ../.env

  postgresql:
    image: bitnami/postgresql:latest
    hostname: postgresql
    ports:
      - '5432:5432'
    env_file:
      - ../src/bot_admin_service/.env
    volumes:
      - ./postgresql/conf/override.conf:/opt/bitnami/postgresql/conf/conf.d/override.conf
      - postgres-data:/bitnami/postgresql
    restart: always
    depends_on:
      - pgbouncer
    healthcheck:
      test: pg_isready -U admin
      interval: 2s
      timeout: 3s
      retries: 40

  pgbouncer:
    image: bitnami/pgbouncer:latest
    hostname: pgbouncer
    ports:
      - "6432:6432"
    env_file:
      - ../src/bot_admin_service/.env
    environment:
      - POSTGRESQL_HOST=postgresql
    volumes:
      - ./pgbouncer/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
    restart: always

volumes:
  redis-data:
    labels:
      keep:
  postgres-data:
    labels:
      keep: